---

- name: Test
  hosts: ROUTERS
  gather_facts: false
  connection: network_cli
  tasks: 
          
      - name: show run
        ios_command:
          commands: 
            - show run
        register: showrun
        
      - name: timestamp
        shell: date +%d-%m-%Y.%H:%M
        register: timestamp  
        
        
      - name: Do Backup
        copy: 
         content: "{{ showrun.stdout[0] }}"
         dest: "/home/nyshaa/Documents/ansible/backup/{{ inventory_hostname }}_{{ timestamp.stdout }} "
         
      - name: backup using git
        git: 
         repo: https://github.com/nyshaa/nyshaa.git
         dest: "/home/nyshaa/Documents/ansible/backup/{{ inventory_hostname }}_{{ timestamp.stdout }} "

